### ISSUE TITLE
RuntimeError: abort(TypeError: Failed to parse URL

### ISSUE THREAD

**Issue by toniton** [multifactor/MFKDF#1]
I get the following error. while trying to use the `mfkdf` lib in nodejs environment.
<img width="863" alt="Screenshot 2023-06-02 at 11 43 34" src="https://github.com/multifactor/MFKDF/assets/5252828/651a95f3-b6cd-4ca1-af8d-7f2295c98bd3">

Environment:
- NodeJS v20.2.0
- Typescript
- NestJS v9.4.2

Do you have any tips or ideas on how to resolve this?

_From the documentation, I understand that this lib is focused on a browser-based implementation. However, I find it suitable for a Backend project which i'm working on._

**Comment by VCNinc** [comment]
Thanks for the report! It seems to be an issue with the argon2-browser package (https://www.npmjs.com/package/argon2-browser). I will take a closer look at this and follow up with more details.

**Comment by toniton** [comment]
That would be great, thanks.

**Comment by VCNinc** [comment]
After investigating the issue further, it seems that a breaking change occurred between Node v16 (for which MFKDF was developed) and v20 (which you are using), which broke the `argon2-browser` package. Thus, the issue seems to be with `argon2-browser` rather than MFKDF. I have considered replacing `argon2-browser` with `node-argon2` and `@node-rs/argon2` but neither are browser compatible and both would cause the browser and node versions of MFKDF to be incompatible, which is undesirable.

I will continue searching for a drop-in solution if one exists. Until then, can you try setting the kdf to something other than argon2 and see if that solves your issue?

**Comment by VCNinc** [comment]
I think this should be resolved now in v1.4.5, which is working for node versions through v20. Let me know if the issue persists.
