### ISSUE TITLE
Search in the docs does not yield relevant results

### ISSUE THREAD

**Issue by quapka** [multifactor/MFKDF#2]
When searching for `RSA, RSA2048` in the search box at https://mfkdf.com/docs/ there are no hits. However, the page https://mfkdf.com/docs/tutorial-09crypto.html does contain relevant information for RSA. From a quick look around I am guessing the search functionality is custom and implemented in [here](https://github.com/multifactor/MFKDF/blob/46dcedc2332cc6e1721a916c2d4dc413d2d9e896/site/docs/scripts/search.js) and only searches the links in the table of contents.

**Comment by VCNinc** [comment]
Thanks for the heads up! This project uses jsdoc to automatically generate documentation. The issue is likely either with jsdoc or the docdash template. While fixing those libraries is not in scope for this project, you are more than welcome to leave a feature request on the jsdoc or docdash repository.
